# Default values.
# This is a YAML-formatted file.
imageTag: latest
# Use nameOverride to override chart name in objects' names
# Default objects' name is {{.Release.Name}}-{{.Chart.Name}}
nameOverride:
replicas: 3
persistence:
# if persistance is disabled, gluster nodes will be started with configuration and data mapped to emptyDir volumes,
#  otherwise persistent volume claims will be created or expected to exist
  enabled: true
# storage class must be specified if you want to use dynamic volume provisioning
  storageClass: glusterfs
  accessMode: ReadWriteMany
# size must be specified if you want to use dynamic volume provisioning
  size: 15Gi
# By default requested resources and resource limits are empty
# Specify some values if you want the pods to be in a different QoS class
resources:
  gluster:
    limits:
      cpu: 0
      memory: 0
    requests:
      cpu: 0
      memory: 0
#resources:
#  gluster:
#    limits:
#      cpu: 1000m
#      memory: 1024Mi
#    requests:
#      cpu: 1000m
#      memory: 1536Mi
