# Default values.
# This is a YAML-formatted file.
imageTag: latest
# Use nameOverride to override chart name in objects' names
# Default objects' name is {{.Release.Name}}-{{.Chart.Name}}
nameOverride:
replicas: 3
# By default requested resources and resource limits are empty
# Specify some values if you want the pods to be in a different QoS class
resources:
  gluster:
    limits:
      cpu: 0
      memory: 0
    requests:
      cpu: 0
      memory: 0
#resources:
#  gluster:
#    limits:
#      cpu: 1000m
#      memory: 1024Mi
#    requests:
#      cpu: 1000m
#      memory: 1536Mi
