apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
spec:
  selector:
    app: {{ template "fullname" . }}
  clusterIP: None
  ports:
  - name: gluster-daemon
    port: 24007
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  serviceName: {{ template "fullname" . }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        app: {{ template "fullname" . }}
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: gluster
        image: gluster/gluster-centos:{{.Values.imageTag}}
        imagePullPolicy: Always
        resources:
{{ .Values.resources.gluster | toYaml | indent 10 }}
        securityContext:
          privileged: true
        ports:
        - name: gluster-daemon
          containerPort: 24007
        volumeMounts:
          - name: glusterd
            mountPath: /var/lib/glusterd
          - name: glusterb
            mountPath: /bricks
      volumes:
      - hostPath:
          path: /data/glusterd
          type: DirectoryOrCreate
        name: glusterd
      - hostPath:
          path: /data/glusterb
          type: DirectoryOrCreate
        name: glusterb
